### PR TITLE
major: full dynamic pages and plain next.js

### PR DESCRIPTION
**Pull request by ovflowd**
## Description

This PR implements the [Discussion started here](https://github.com/nodejs/nodejs.org/discussions/5442) on leaving Nextra in favour of a vanilla Next.js experience.

Truth be told, as mentioned in the discussion, we finally matured in a way that we don't need Nextra anymore.

This PR is a draft and the description will be updated with way more details. Not to mention some files and docs need to be updated.

### CODE REVIEW

**Comment by ovflowd** [comment]
Misleading. Because these are still pages. They're not just "content"

**Comment by AugustinMauroy** [comment]
`_pages` because by default on finder file starting with a dot aren't displayed

**Comment by ovflowd** [comment]
> _pages because by default on finder file starting with a dot aren't displayed

Hmm, I guess having both `pages` and `.pages` or `pages` and `_pages` sounds confusing.

I'm open to suggestions. Maybe `routes` or `next-pages`, but I guess `content` in theory would do the trick.

**Comment by AugustinMauroy** [comment]
`routes` we expect `.tsx` files. `next-pages` a little better. It's true that content isn't 100% right, but it's common.

**Comment by ovflowd** [comment]
Merging this into the main PR on `nodejs.org`

**Pull request merged**
